version: "2"

linters:
  default: "standard"
  enable:
    - lll
    - gocyclo
    - goconst
    - nestif
    - tagliatelle
    - govet
  settings:
    gocyclo:
      min-complexity: 10
    govet:
      enable-all: true
      disable:
        - shadow
formatters:
  enable:
    - gofumpt
run:
  timeout: 5m
  modules-download-mode: readonly
